declare function DeleteFunctionReference(referenceIdentity : string) : void;
declare function CancelEvent() : void;
declare function AddConvarChangeListener(conVarFilter : string , handler : Function) : number;
declare function AddStateBagChangeHandler(keyFilter : string , bagFilter : string , handler : Function) : number;
declare function EnsureEntityStateBag(entity : number) : void;
declare function DoesTrainStopAtStations(train : number) : boolean;
declare function DuplicateFunctionReference(referenceIdentity : string) : string;
declare function ExecuteCommand(commandString : string) : void;
declare function FormatStackTrace(traceData : object) : string;
declare function GetConvar(varName : string , default_ : string) : string;
declare function GetConvarFloat(varName : string , defaultValue : number) : number;
declare function GetCurrentResourceName() : string;
declare function GetInstanceId() : number;
declare function GetEntityFromStateBagName(bagName : string) : number;
declare function GetGameName() : string;
declare function GetConvarInt(varName : string , default_ : number) : number;
declare function GetEntitiesInRadius(x : number , y : number , z : number , radius : number , entityType : number , sortByDistance : boolean , models : object) : object;
declare function GetConvarBool(varName : string , defaultValue : boolean) : boolean;
declare function GetGamePool(poolName : string) : object;
declare function GetInvokingResource() : string;
declare function GetGameBuildNumber() : number;
declare function GetNumResources() : number;
declare function GetPlayerMeleeWeaponDamageModifier(playerId : number) : number;
declare function GetNumResourceMetadata(resourceName : string , metadataKey : string) : number;
declare function GetStateBagKeys(bagName : string) : object;
declare function GetResourceMetadata(resourceName : string , metadataKey : string , index : number) : string;
declare function GetPlayerFromStateBagName(bagName : string) : number;
declare function GetStateBagValue(bagName : string , key : string) : object;
declare function GetPlayerWeaponDefenseModifier2(playerId : number) : number;
declare function GetResourceState(resourceName : string) : string;
declare function GetPlayerWeaponDefenseModifier(playerId : number) : number;
declare function GetResourceCommands(resource : string) : object;
declare function GetTrainTrackIndex(train : number) : number;
declare function GetTrainDirection(train : number) : boolean;
declare function GetTrainState(train : number) : number;
declare function GetRegisteredCommands() : object;
declare function GetPlayerWeaponDamageModifier(playerId : number) : number;
declare function GetResourceByFindIndex(findIndex : number) : string;
declare function GetTrainCruiseSpeed(train : number) : number;
declare function GetVehicleHandbrake(vehicle : number) : boolean;
declare function GetVehicleType(vehicle : number) : string;
declare function GetVehicleSteeringAngle(vehicle : number) : number;
declare function IsAceAllowed(object : string) : boolean;
declare function IsDuplicityVersion() : boolean;
declare function IsEntityPositionFrozen(entity : number) : boolean;
declare function IsVehicleEngineStarting(vehicle : number) : boolean;
declare function IsPrincipalAceAllowed(principal : string , object : string) : boolean;
declare function LoadResourceFile(resourceName : string , fileName : string) : string;
declare function NetworkGetEntityOwner(entity : number) : number;
declare function ProfilerEnterScope(scopeName : string) : void;
declare function RegisterResourceAsEventHandler(eventName : string) : void;
declare function ProfilerExitScope() : void;
declare function ProfilerIsRecording() : boolean;
declare function RegisterCommand(commandName : string , handler : Function , restricted : boolean) : void;
declare function RemoveConvarChangeListener(cookie : number) : void;
declare function RemoveStateBagChangeHandler(cookie : number) : void;
declare function SetStateBagValue(bagName : string , keyName : string , valueData : string , valueLength : number , replicated : boolean) : void;
declare function DeleteResourceKvp(key : string) : void;
declare function WasEventCanceled() : boolean;
declare function TriggerEventInternal(eventName : string , eventPayload : string , payloadLength : number) : void;
declare function StateBagHasKey(bagName : string , key : string) : boolean;
declare function GetResourceKvpString(key : string) : string;
declare function EndFindKvp(handle : number) : void;
declare function GetResourceKvpInt(key : string) : number;
declare function SetResourceKvpFloatNoSync(key : string , value : number) : void;
declare function FindKvp(handle : number) : string;
declare function SetResourceKvp(key : string , value : string) : void;
declare function SetResourceKvpIntNoSync(key : string , value : number) : void;
declare function SetResourceKvpFloat(key : string , value : number) : void;
declare function DeleteResourceKvpNoSync(key : string) : void;
declare function StartFindKvp(prefix : string) : number;
declare function GetResourceKvpFloat(key : string) : number;
declare function SetResourceKvpInt(key : string , value : number) : void;
declare function SetResourceKvpNoSync(key : string , value : string) : void;
